config/routes.rb
Rails.application.routes.draw do
  get 'bcl/index'
  resources :categories, only: [:index, :new, :edit, :create, :update, :destroy]
  resources :blogs do
    collection do
      get :management
    end
  end
  resources :contacts, only: [:create, :new]
  get 'contact', to: 'contacts#new'
  get 'static_pages/home'
  get '/admin/login', to: 'sessions#new'
  post '/admin/login', to: 'sessions#create'

  root to: 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_and_belongs_to_many :categories
  validates :title, :body,
            presence: true
  validates :title,
            length: {maximum: 255}, allow_blank: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :blogs
  validates :name,
            presence: true
  validates :name,
            length: {maximum: 255}, allow_blank: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A\d{10}\z|\A\d{11}\z/
  validates :name, :email, :telephone, :message,
            presence: true
  validates :company, :name, :email,
            length: {maximum: 255}, allow_blank: true
  validates :email,
            format: {with: VALID_EMAIL_REGEX}, allow_blank: true
  validates :telephone,
            format: {with: VALID_PHONE_REGEX}, allow_blank: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :check_logined

  private

  def check_logined
    if session[:user_id]
      begin
        user = User.find(session[:user_id])
      rescue ActiveRecord::RecordNotFound
        reset_session
      end
    end
    unless user
      redirect_to admin_login_url
    end
  end

end

app/controllers/bcl_controller.rb
class BclController < ApplicationController
  skip_before_action :check_logined

  def index
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = Rails.application.credentials.twitter[:api_key]
      config.consumer_secret = Rails.application.credentials.twitter[:api_secret_key]
      config.access_token = Rails.application.credentials.twitter[:access_token]
      config.access_token_secret = Rails.application.credentials.twitter[:access_token_secret]
    end
    @count_toyama = client.user("T_birds").followers_count
    @count_niigata = client.user("Albi_BC_PR").followers_count
    @count_sinano = client.user("GrazieClub").followers_count
    @count_ishikawa = client.user("I_Million_Stars").followers_count
    @count_shiga = client.user("shigaunitedbc").followers_count
    @count_ibaraki = client.user("ibaraki_planets").followers_count
    @count_fukushima = client.user("F_REDHOPES").followers_count
    @count_saitama = client.user("musashi_bears").followers_count
    @count_tochigi = client.user("tochigi_gb").followers_count
    @count_gunma = client.user("kyumaraima").followers_count
    @count_kanagawa = client.user("k_futuredreams").followers_count
    @count_fukui = client.user("Fukui_Raptors").followers_count
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  skip_before_action :check_logined, only: [:index, :show]
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category]
      @category = Category.find_by(id: params[:category])
      @blogs = @category.blogs.order(created_at: :desc)
    else
      @blogs = Blog.all.order(created_at: :desc)
    end
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      redirect_to management_blogs_url, notice: 'ブログ記事の作成に成功しました。'
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to management_blogs_url, notice: 'ブログ記事の更新に成功しました。'
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to management_blogs_url, notice: 'ブログ記事の削除に成功しました。'
  end

  def management
    @blogs = Blog.all.order(created_at: :desc)
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body, :created_at, category_ids: [])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_url, notice: 'カテゴリの作成に成功しました。'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to categories_url, notice: 'カテゴリの更新に成功しました。'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'カテゴリの削除に成功しました。'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :check_logined

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      NoticeMailer.sendmail_contact(@contact).deliver
      redirect_to new_contact_url, notice: '問い合わせの送信に成功しました。'
    else
      render :new
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:company, :name, :email, :telephone, :message)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :check_logined

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      reset_session
      session[:user_id] = user.id
      redirect_to management_blogs_url, notice: 'ログインしました。'
    else
      flash.now[:danger] = '入力値が誤っています。'
      render :new
    end
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :check_logined

  def home
    @blogs = Blog.all.order(created_at: :desc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    render_options = {
        filter_html: false,
        hard_wrap: true
    }
    # renderer = Redcarpet::Render::HTML.new(render_options)
    renderer = Redcarpet::Render::CustomMarkdownRenderer.new(render_options)

    extensions = {
        autolink: true,
        fenced_code_blocks: true,
        lax_spacing: true,
        no_intra_emphasis: true,
        strikethrough: true,
        superscript: true,
        tables: true,
    }
    Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
  end
end

app/views/bcl/index.html.haml
.container
  %h1 BCL_follower
  %p
    ※取得に失敗する場合は時間を空けてから再度アクセスしてください。
  = "栃木GB #{@count_tochigi}"
  %br
  = "新潟ABC #{@count_niigata}"
  %br
  = "富山GRNTB #{@count_toyama}"
  %br
  = "石川MS #{@count_ishikawa}"
  %br
  = "福島RH #{@count_fukushima}"
  %br
  = "群馬DP #{@count_gunma}"
  %br
  = "神奈川FD #{@count_kanagawa}"
  %br
  = "信濃GS #{@count_sinano}"
  %br
  = "茨城AP #{@count_ibaraki}"
  %br
  = "埼玉武蔵HB #{@count_saitama}"
  %br
  = "オセアン滋賀UBC #{@count_shiga}"
  %br
  = "福井WR #{@count_fukui}"

app/views/blogs/_form.html.haml
= simple_form_for(@blog) do |f|
  = f.input :title
  .blog-textarea
    = f.input :body
  = f.association :categories, as: :check_boxes, label: 'カテゴリ'
  = f.input :created_at, html5: true
  = f.button :submit, class: 'page-link text-dark d-inline-block'

app/views/blogs/edit.html.haml
.container

  %h1 ブログ記事編集

  = render 'form'

app/views/blogs/index.html.haml
.container

  %h1 blog

  - if @category
    .mt-3
      = "category: #{@category.name}"

  - @blogs.each do |blog|
    .article
      .text-center.mt-5
        %time.last-updated
          last updated:
          = l blog.updated_at
        %h2.mt-2
          = link_to blog.title, blog
        .mt-3
          - blog.categories.each do |category|
            .category.ml-1.px-1
              = link_to category.name, blogs_path(category: category.id)
      .mt-4
        = markdown blog.body

app/views/blogs/management.html.haml
.container

  %h1.mb-4.float-left 記事管理

  .float-right.mt-3
    = link_to '作成', new_blog_path, class: 'page-link text-dark d-inline-block'

  .clearfix

  - if notice
    .alert.alert-success.mb-4.mt-3{role: "alert"}
      = notice

  %table.table.table-striped.table-sm.table-bordered
    %thead
      %tr
        %th タイトル
        %th タグ
        %th 投稿日時
        %th{colspan: 2}
    %tbody
      - @blogs.each do |blog|
        %tr
          %td
            = link_to blog.title, blog
          %td
            - blog.categories.each do |category|
              = link_to category.name, blogs_path(category: category.id)
          %td
            = l blog.created_at
          %td.cell-link.text-center
            = link_to '編集', edit_blog_path(blog)
          %td.cell-link.text-center
            = link_to '削除', blog, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }

app/views/blogs/new.html.haml
.container

  %h1 ブログ記事投稿

  = render 'form'

app/views/blogs/show.html.haml
.container

  %h1 blog

  .article
    .text-center.mt-4
      %time.last-updated
        last updated:
        = l @blog.updated_at
      %h2.mt-2
        = @blog.title
      .mt-3
        - @blog.categories.each do |category|
          .category.ml-1.px-1
            = link_to category.name, blogs_path(category: category.id)
    .mt-4
      = markdown @blog.body

app/views/categories/_form.html.haml
= simple_form_for(@category) do |f|
  = f.input :name
  = f.button :submit, class: 'page-link text-dark d-inline-block'

app/views/categories/edit.html.haml
.container

  %h1 カテゴリ編集

  = render 'form'

app/views/categories/index.html.haml
.container

  %h1.mb-4.float-left カテゴリ

  .float-right.mt-3
    = link_to '作成', new_category_path, class: 'page-link text-dark d-inline-block'

  %table.table.table-sm.table-bordered.text-center
    %tbody
      - @categories.each do |category|
        %tr
          %td.font-weight-bold{style: 'border: 2px solid'}
            = category.name
          %td.cell-link
            = link_to '編集', edit_category_path(category)
          %td.cell-link
            = link_to '削除', category, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }

app/views/categories/new.html.haml
.container

  %h1 カテゴリ作成

  = render 'form'

app/views/contacts/_form.html.haml
= simple_form_for @contact do |f|
  = f.input :company
  = f.input :name
  = f.input :email
  = f.input :telephone
  = f.input :message
  = f.button :submit, '送信する', class: 'page-link text-dark d-inline-block', data: { confirm: 'この内容で送信してもよろしいですか？' }

app/views/contacts/new.html.haml
.container

  %h1 contact

  - if notice
    .alert.alert-success.my-4{role: "alert"}
      = notice

  = render 'form'

app/views/layouts/application.html.haml
!!!
%html.h-100
  %head
    %title TsubasaYoshida
    = csrf_meta_tags
    = csp_meta_tag
    %meta{charset: 'utf-8'}/
    %meta{'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}/
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1'}/
    %meta{'http-equiv': 'content-language', content: 'ja'}/
    %meta{name: 'description', content: '札幌のプログラマ 吉田翼です。Railsのお仕事を探しています。'}/
    /[if lt IE 9]
      %script{src: 'https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'}
      %script{src: 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js'}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'

    -#Bootstrap導入
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body.d-flex.flex-column.h-100
    %header.pb-3.pb-sm-4
      %nav.navbar.navbar-expand-md.navbar-dark.bg-dark.sticky-top
        .container
          = link_to 'Tsubasa Yoshida', :root, class: 'navbar-brand text-decoration-none'
          %button.navbar-toggler{type: 'button', 'data-toggle': 'collapse', 'data-target': '#navbar-content', 'aria-controls': 'navbar-content', 'aria-expanded': 'false', 'aria-label': 'Toggle navigation'}
            %span.navbar-toggler-icon
          .collapse.navbar-collapse{id: 'navbar-content'}
            %ul.navbar-nav.ml-auto
              %li.nav-item.pt-1
                = link_to 'profile', '#', class: 'nav-link'
              %li.nav-item.pt-1
                = link_to 'career', '#', class: 'nav-link'
              %li.nav-item.pt-1
                = link_to 'work', '#', class: 'nav-link'
              %li.nav-item.pt-1
                = link_to 'bookshelf', '#', class: 'nav-link'
              %li.nav-item.pt-1
                = link_to 'blog', blogs_path, class: 'nav-link'
              %li.nav-item.pt-1
                = link_to 'contact', contact_path, class: 'nav-link'
              %li.nav-item.pt-1.mr-3
                = link_to 'bcl_follower', bcl_index_path, class: 'nav-link'
    %main.mb-5
      = yield
    %footer.text-center.mt-auto
      %nav.navbar.navbar-expand.navbar-dark.bg-dark.justify-content-center.pt-3
        %ul.navbar-nav
          %li.nav-item.pt-1
            = link_to 'GitHub', 'https://github.com/TsubasaYoshida', class: 'nav-link'
          %li.nav-item.pt-1
            = link_to 'Twitter', 'https://twitter.com/tsubasa_upset', class: 'nav-link'
          %li.nav-item.pt-1
            = link_to 'Qiita', 'https://qiita.com/tsubasa_upset', class: 'nav-link'
          %li.nav-item.pt-1
            = link_to 'Wantedly', 'https://www.wantedly.com/users/70103878', class: 'nav-link'
      .bg-dark.pb-4
        &#169; 2019 Tsubasa Yoshida

app/views/static_pages/home.html.haml
.container
  %h1.mb-0.font-24px
    \# Welcome to my website.
  %p.ml-2
    \- I am a professional programmer.

  .my-4

  %h2.font-22px
    = link_to '## blog', blogs_path

  .my-3

  .row
    - @blogs.each do |blog|
      .col-sm-4
        .card.mb-4
          = link_to blog do
            .card-body
              .card-title.font-18px.font-weight-bold
                = blog.title
              %p.card-text
                = truncate blog.body, length: 100, omission: ' …'

  .my-4

  %h2.font-22px
    = link_to '## work'

  .my-3